### ISSUE TITLE
Stuck at Got response code 404

### ISSUE THREAD

**Issue by solray** [JustinAiken/jekyll-gitlab-letsencrypt#1]
Wonderful idea for a plugin. Unfortunately, the process hangs even after new commit process has passed —

`Got response code 404, waiting 15 seconds...`
`Got response code 404, waiting 15 seconds...`
`Got response code 404, waiting 15 seconds...`

**Comment by JustinAiken** [comment]
- Do you have the CI setup to autobuild/deploy your pages on a commit?
- Did the build succeed?
- The plugin should give you the link it's trying to hit - does going to it manually work for you, or is it 404'ing too?
  - It might be a matter of a missing or extra `/` passed on your pretty permalink options..
  - Or some other way it's set up

If you want to gist more info, I'll be happy to 👀  more into it..

**Comment by solray** [comment]
- Yes to autobuild/deploy pages on a commit.
- Yes, build succeeded.
- Ended up going the manual way and not using the plugin, although it will be great it can be resolved by next TLS expiration date.

You can close the ticket for now, or if you like to look into it more I can try and help with debugging.

Thank you Justin.

**Comment by jkrmr** [comment]
I'm seeing 301 redirects

```
Waiting 120 seconds before we start checking for challenge..
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
Got response code 301, waiting 15 seconds...
```

**Comment by JustinAiken** [comment]
Hmm, try `curl -I`'ing the url it's trying to get your challenge at... see where it's attempting to redirect to.

**Comment by jkrmr** [comment]
Ah. It's because it's sending a request using http but I have a rule set to redirect all http traffic to https. I modified this to get it working:

https://github.com/JustinAiken/jekyll-gitlab-letsencrypt/blob/3efb9af006a82b823b9807144d985b0363deb46f/lib/jekyll/gitlab/letsencrypt/process.rb#L109-L113

**Comment by JustinAiken** [comment]
>  I have a rule set to redirect all http traffic to https. 

How did you do that on Gitlab!?

>  I modified this to get it working:

See if it looks #3 would allow to use this without local file modifications

**Comment by jkrmr** [comment]
> How did you do that on Gitlab!?

I think GitLab might do that automatically for pages served from `gitlab.io`, but for a custom domain I had to set up cloudflare as my nameserver and set up a page rule:

<img width="747" alt="namecheap nameserver" src="https://user-images.githubusercontent.com/4433943/30036390-eb2ecb10-9180-11e7-92c3-08cc37275135.png">

<img width="1007" alt="cloudflare page rule" src="https://user-images.githubusercontent.com/4433943/30036391-eb2f199e-9180-11e7-8830-62f79fc7a8c3.png">

**Comment by JustinAiken** [comment]
Pushed out as [v0.0.2](https://github.com/JustinAiken/jekyll-gitlab-letsencrypt/releases/tag/v0.0.2) - 90 days from now you should be able to just update the gem and your config, without changes!

**Comment by jkrmr** [comment]
Nice! Thanks man 🎉
