### ISSUE TITLE
hostname "domainname.com" does not match the server certificate

### ISSUE THREAD

**Issue by justinechacko** [JustinAiken/jekyll-gitlab-letsencrypt#12]
I followed set up instructions. When I issue bundle exec jekyll letsencrypt I got like below
```
Configuration file: /home/justinechacko/www/main/_config.yml
Registering contact@justinechacko.in to https://acme-v01.api.letsencrypt.org/... 
Pushing file to Gitlab 
Commiting challenge file as letsencrypt.html 
Done Commiting! Check https://gitlab.com/bpmottathai/main/commits/master 
Going to check https://justinechacko.in/.well-known/acme-challenge/87AXszq5OEf_GQ7oRzYAM1LkIza9pKEuCEe4_LZkSIE for the challenge to be present... 
Waiting 120 seconds before we start checking for challenge.. 
jekyll 3.4.0 | Error:  hostname "justinechacko.in" does not match the server certificate
```
Where is the server certificate, I am a newbie, do I need to install https://github.com/rolodato/gitlab-letsencrypt

**Comment by JustinAiken** [comment]
Try setting your `scheme` to `http` instead of `https` - you have to check the challenge url over plain old `http` instead of `https`

Should say `Going to check http://justinechacko.in/.well-known...` instead of `Going to check https://justinechacko.in/.well-known...`

> do I need to install https://github.com/rolodato/gitlab-letsencrypt

Nope, not at all!

**Comment by justinechacko** [comment]
```
bundle exec jekyll letsencrypt
Configuration file: /home/justinechacko/www/main/_config.yml
Registering contact@justinechacko.in to https://acme-v01.api.letsencrypt.org/... 
Pushing file to Gitlab 
Commiting challenge file as letsencrypt.html 
Done Commiting! Check https://gitlab.com/bpmottathai/main/commits/master 
Going to check http://justinechacko.in/.well-known/acme-challenge/rwhX92k_s7bvaVQo6kj_5Q0aa2m_xczPLmS-vH_zvNU for the challenge to be present... 
Waiting 120 seconds before we start checking for challenge.. 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
Got response code 404, waiting 15 seconds... 
^C/var/lib/gems/2.3.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/process.rb:55:in `sleep': Interrupt
	from /var/lib/gems/2.3.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/process.rb:55:in `block in wait_until_challenge_is_present'
	from /var/lib/gems/2.3.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/process.rb:48:in `loop'
	from /var/lib/gems/2.3.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/process.rb:48:in `wait_until_challenge_is_present'
	from /var/lib/gems/2.3.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/process.rb:25:in `process!'
	from /var/lib/gems/2.3.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/gitlab/letsencrypt/process.rb:12:in `process!'
	from /var/lib/gems/2.3.0/gems/jekyll-gitlab-letsencrypt-0.2.0/lib/jekyll/commands/gitlab/letsencrypt.rb:10:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.3.0/gems/jekyll-3.4.0/exe/jekyll:13:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

```

I did ctrl+c as it repeats 404 error.  For your info I didn't add any certificate to my domain name. Do I need to add certificate? I didn't go to letsencrypt site and not configured anything...

**Comment by JustinAiken** [comment]
> I did ctrl+c as it repeats 404 error.

It's checking for the challenge to be there... looks like it's still not.  Do you have gitlab CI setup such that pushing to `master` triggers an automated deployment of your jekyll blog?

> For your info I didn't add any certificate to my domain name. Do I need to add certificate? I didn't go to letsencrypt site and not configured anything...Do I need to go certbot.eff.org

Don't need to do any of that, that's what this plugin is for :)

**Comment by justinechacko** [comment]
> Gitlab CI setup such that when you push to master (or your preferred branch), your changes are deployed live

How to do it?

**Comment by JustinAiken** [comment]
Ah yes, this plugin handles all of the letsencrypting/cert-grabbing for you, but first you have to have Gitlab CI set up such that pushes to `master` (or some other branch) autodeploy the code changes live for you..

Try one of these tutorials:
- https://www.redpill-linpro.com/sysadvent/2016/12/03/jekyll-gitlab-ci.html
- https://rpadovani.com/jekyll-autodeploy-gitlab-ci
- https://www.chenhuijing.com/blog/hosting-static-site-gitlab-pages/#%F0%9F%8F%80
- https://jennifermack.net/2017/02/04/bootstrapping-a-jekyll-blog-using-gitlab/

Once you get to the point where pushing new code to `master` results in live changes happening, this plugin should do the remaining magic 🎩  to get https'd up

**Comment by justinechacko** [comment]
Okey, As a newbie I have some confusion. Following is my .gitlab-ci.yml
```
image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - export LC_ALL="C.UTF-8"
  - export LANG="en_US.UTF-8"
  - export LANGUAGE="en_US.UTF-8"
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
```
Is it enough? Thanks.

**Comment by justinechacko** [comment]
Previously this domain connected to firebase and I didn't disconnect it

**Comment by JustinAiken** [comment]
That looks like it should work now.. if you rerun the `bundle exec jekyll letsencrypt` now, it should sail through

**Comment by justinechacko** [comment]
Not working for me. What step I am missing??? 
[![Screenshot_from_2018-02-24_10-37-37.png](https://s14.postimg.org/a1z25v2a9/Screenshot_from_2018-02-24_10-37-37.png)](https://postimg.org/image/411d8sfnx/)

**Comment by justinechacko** [comment]
I think I got something.... jekyll-gitlab-letsencrypt gem is not installing in pipeline...!!

**Comment by justinechacko** [comment]
File is in root folder and permalink is` ./.well-known/acme-challenge/xNwynQAyZHTpbbuVgJS22lKcg8XkWKcglm_emfYJDEI`

Any problem?

**Comment by justinechacko** [comment]
please look into files. https://drive.google.com/file/d/1N2RvbRtUzimrQ2twdnkCdfZUEgknxpvl/view?usp=sharing

site is justinechacko.in

**Comment by justinechacko** [comment]
HI @JustinAiken , What step I am missing??

**Comment by JustinAiken** [comment]
Removing this gem/plugin from the equation for a moment..
- Make sure your local `master` branch and the remote gitlab `master` are in sync
- If you make a change (add "hello world" to a blog post or something) and commit/push it to `master`
  - Does it kick off a pipeline build on Gitlab?
  - Does the pipeline build on Gitlab succeed?
  - Does it kick off a Gitlab-internal deploy pipeline?
  - Does your changes eventually make it live onto the justinechacko.in site?

**Comment by justinechacko** [comment]
[![Screenshot_from_2018-02-27_13-24-53.png](https://s17.postimg.org/sd278lpvz/Screenshot_from_2018-02-27_13-24-53.png)](https://postimg.org/image/gny7kmyx7/)

I think answer to all your question is "yes".

But I don't know the difference between  

> Does it kick off a pipeline build on Gitlab?

and 

> Does it kick off a Gitlab-internal deploy pipeline?

**Comment by JustinAiken** [comment]
That looks like it should be good..

Now locally (make sure you're up-to-date with `master`), run `bundle exec jekyll letsencrypt`..
- It should create a commit for (remotely, it won't show up locally until you `git pull` it back down
  - That commit will add/changes `lets.html`
  - Which the pipeline should push out
  - The plugin will keep 404 and checking.. let it go on all the way until your build is done
  - If you can see the newly added page, and acme can see the newly added page, you're good - it'll go from there
  - If you can see the newly added page, but the letsencrypt plugin still says it's not found, then there's still a jekyll-letsencrypt config problem, and let me know from there 
  - If you can't see the newly added page at, something is wrong with the pipeline config outside of this plugin...

**Comment by justinechacko** [comment]
Hi thanks for reply. Newly added page means letsencrypt.html?

**Comment by JustinAiken** [comment]
Er yeah, `letsencrypt.html` (it's configurable - my local is setup as `lets.html`, but looking at your config above, it's `letsencrypt.html` for you

**Comment by justinechacko** [comment]
I already show you that there is letsencrypt file. But the problem is it is located at root folder not at the path ./.well-known/acme-challenge/xNwynQAyZHTpbbuVgJS22lKcg8XkWKcglm_emfYJDEI

**Comment by justinechacko** [comment]
my .gitignore file 

```
_site
.sass-cache
.jekyll-metadata
public/
```

**Comment by JustinAiken** [comment]
- Maybe try `pretty_url: true` ?  
- Shouldn't need to remove `public/` from `gitignore`

**Comment by justinechacko** [comment]
Yay! I think it is working now.!!

```
Waiting 120 seconds before we start checking for challenge.. 
Got response code 200, file is present! 
Requesting verification... 
Challenge is valid! 
Updating domain justinechacko.in pages setting with new certificates.. 
           Success! 
```

When ssl will be enabled. At present no ssl for me. Will it takes time? Also Can I have ssl to my subdomain also like http://songs.justinechacko.in Thanks.

**Comment by justinechacko** [comment]
> I probably won't add multiple domain support myself

Can I add ssl manually by following [This tutorial](https://about.gitlab.com/2016/04/11/tutorial-securing-your-gitlab-pages-with-tls-and-letsencrypt/)

**Comment by justinechacko** [comment]
Closing as resolved...

**Comment by justinechacko** [comment]
Can I use same email address for subdomain too

**Comment by JustinAiken** [comment]
Yep, email really isn't that important
