### ISSUE TITLE
How auto renew work?

### ISSUE THREAD

**Issue by justinechacko** [JustinAiken/jekyll-gitlab-letsencrypt#13]
Hi, thanks for creating this plugin @JustinAiken 
Do I need to keep local repo to auto renew SSL? Also if I have private repo and using token in config.yml will it become public anyway?

**Comment by JustinAiken** [comment]
> How auto renew work? 

It doesn't! 😛 

> Do I need to keep local repo to auto renew SSL?

Yeah.. I guess you could set up your repo on a VPS and set a cron to auto renew every 80 days, but I usually just wait until I get the email from letsencrypt that it's about to expire, then `cd /path/to/my/blog && bundle exec jekyll letsencrypt` - not *quite* painful enough to automate

>  Also if I have private repo and using token in config.yml will it become public anyway?

You don't have have to put the token in `config.yml` - instead you can do `GITLAB_TOKEN='much_secret' bundle exec jekyll letsencrypt`

**Comment by justinechacko** [comment]
Okey, thanks. Closed...
