### ISSUE TITLE
404 - *.html file extension?

### ISSUE THREAD

**Issue by Yttrium-tYcLief** [JustinAiken/jekyll-gitlab-letsencrypt#19]
I've been banging my head against the wall trying to get this set up, and I think I'm nearly there, but now I'm getting error 404's when trying to read back the validation code. You know the error:

`Got response code 404, waiting 15 seconds...`
`Got response code 404, waiting 15 seconds...`
`Got response code 404, waiting 15 seconds...`

Now, in trying to debug this, I think I've figured out what's going on. The trouble is that I don't really know how to fix it in a consistent way. I could override it manually, but it would be a problem for every renewal job in the future.

By checking the Gitlab job status after letsencrypt pushes its commit, I can browse through the job artifacts and see exactly what data it's spitting out. It properly generates the `domainname.com/.well-known/acme-challenge/` folder structure, however the file it creates in that folder is called `xY6PmHQcg9rp5j2vkdDWS3etCbwFE7MfuBa_zZ8sGqR.html`. If I manually try to load that file in Chrome, it shows the response data just fine. 

However, letsencrypt isn't looking for `xY6PmHQcg9rp5j2vkdDWS3etCbwFE7MfuBa_zZ8sGqR.html`, it's looking for `xY6PmHQcg9rp5j2vkdDWS3etCbwFE7MfuBa_zZ8sGqR`, and receiving a 404.

Is there any way I can either modify my configuration to permit this anomaly, or would it be possible to add a config option for this type of thing upstream? Keep in mind that I have absolutely no experience writing anything in Ruby, so I wouldn't be able to make a PR with the feature, or even fix it myself.

**Comment by JustinAiken** [comment]
Jekyll gives you a `pretty_url` option, so that when you do `some_link/` with a trailing slash, it'll serve up the URL without needing the `.html` added at the end.  If you have that setting set in jekyll, you can turn on `pretty_url` in this config to make that work..

Does that work for you, or do you need an option to add the full `.html` ?

**Comment by JustinAiken** [comment]
Created a branch that does that: https://github.com/JustinAiken/jekyll-gitlab-letsencrypt/tree/feature/opt_append_html

In your jekyll app, try it out:

## Gemfile

```ruby
# replace
gem "jekyll-gitlab-letsencrypt"
with 
gem "jekyll-gitlab-letsencrypt", github: "JustinAiken/jekyll-gitlab-letsencrypt', branch: "opt_append_html"
```

## Jekyll config

```yaml
gitlab-letsencrypt:
  ... 
  # Add this:
  append_html: true
```

Then give it a try - if it works for you I'll merge it in and push out a new release

**Comment by JustinAiken** [comment]
Ah, try this... `bundle update` to pull in the [latest commit](https://github.com/JustinAiken/jekyll-gitlab-letsencrypt/commit/161dc3a10b4935a1161a5fd19a2451ebfcf03b54), then change the config to:

```yaml
gitlab-letsencrypt:
  ... 
  # Add this:
  append_str: "index.html"
```

and take out the `append_html` line

**Comment by Yttrium-tYcLief** [comment]
Success! Sort of.

![image](https://user-images.githubusercontent.com/1037011/44245738-46405900-a1a8-11e8-9b79-3607c88fd96b.png)

The file definitely outputs correctly, and for the first time ever, letsencrypt determines a successful validation. That being said, I... don't know what this error is really pointing to. Googling around doesn't show anything obvious. Any ideas?

I'm going to go ahead and close this issue though, since your new branch has definitely fixed the problem the issue was about.

**Comment by Yttrium-tYcLief** [comment]
Yeah, I've been trying every once and awhile for the past two days or so, just in case it was a load issue on their servers. It times out every single time. There was one time where Gitlab was under such heavy load that it took more than 120 seconds to finish processing, and I got a bad nonce error that time, but right after it said "bad nonce! trying again..", it quit with the same timeout error.

Is 120 seconds too long of a delay for letsencrypt? I would assume not, especially because it's the default setting. I can't really try any delays lower than that though, because that's about how long it takes Gitlab to process my site normally.

**Comment by Yttrium-tYcLief** [comment]
I definitely understood where the issue was - that's why I stated "too long of a delay for letsencrypt", as in the API.

Unfortunately despite trying almost every day, it never seems to communicate properly with letsencrypt.

I'm gunna try later from a different computer, maybe it'll work then. I'll also try another internet connection in case it's the network.

**Comment by bear454** [comment]
Any chance the "feature/opt_append_html" is going to be merged into master?

**Comment by pcercuei** [comment]
Same question.

**Comment by JustinAiken** [comment]
@bear454 @pcercuei - Sorry for the delay..

Just merged that, and pushed out a new release: https://github.com/JustinAiken/jekyll-gitlab-letsencrypt/releases/tag/v0.4.1 

Hope it helps!

**Comment by bear454** [comment]
> @bear454 @pcercuei - Sorry for the delay..
> 
> Just merged that, and pushed out a new release: https://github.com/JustinAiken/jekyll-gitlab-letsencrypt/releases/tag/v0.4.1
> 
> Hope it helps!

I ended up using certbot, and modifying the files in CI: 
https://gitlab.com/lfnw/lfnw-blog/blob/master/.gitlab-ci.yml#L31
