### ISSUE TITLE
How does the plugin handle certificate renewals?

### ISSUE THREAD

**Issue by asarkar** [JustinAiken/jekyll-gitlab-letsencrypt#5]
...no mention of renewals in the doc.

**Comment by JustinAiken** [comment]
Afraid there's not really much a renewal process... every 90 days or so you have to do the `jekyll letsencrypt` dance from scratch.  If Gitlab had an API endpoint to post the new certs, it could be fully automated and stashed in a cron job.

**Comment by asarkar** [comment]
I moved to [Netlify](https://www.netlify.com/). They have everything I need for *free*, and I can keep the blog on GitHub (though not as GH Pages). GitLab has around 10k bugs open, which doesn't say much about the quality control, and their deploy fails randomly.

**Comment by b-long** [comment]
@JustinAiken Couldn't renewal be automated using the cron-like Pipeline scheduling in GitLab ? 

More info: https://docs.gitlab.com/ce/user/project/pipelines/schedules.html 

I think if possible, your code and the workflow would be valuable to a wide variety of people.

**Comment by JustinAiken** [comment]
The problem is, it could run automatically in the cronish Pipeline to generate a new certificate... but it wouldn't get entered in.  One must still manually go to the domains page, delete the domain, then readd it with the freshly-generated certificate..

**Comment by b-long** [comment]
Ah, I see.  My mistake.
