### ISSUE TITLE
Use Pages API

### ISSUE THREAD

**Issue by To1ne** [JustinAiken/jekyll-gitlab-letsencrypt#7]
[Since](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/13917) GitLab 10.2 there is [an API](https://docs.gitlab.com/ee/api/pages_domains.html#update-pages-domain) to update domain info and TLS certificate. It would be awesome to have this integrated.

**Comment by JustinAiken** [comment]
Ooh yay!  I'll add that in either late this week or early next

**Comment by JustinAiken** [comment]
@To1ne - Could you try using the branch in #8 and see if it works for you?  It works for me, but I'd love a second sample before merging and releasing a new version...

**Comment by ANGOmarcello** [comment]
@JustinAiken I could try the branch in #8 out if you can give me a brief info on how to compile it.

**Comment by JustinAiken** [comment]
No need to compile!  Just point to that branch in your `Gemfile`:

```ruby
# Replace
  gem "jekyll-gitlab-letsencrypt"
# With:
  gem "jekyll-gitlab-letsencrypt", github: "JustinAiken/jekyll-gitlab-letsencrypt", branch: "feature/pages_api"
```

Run `bundle install`, and then `jekyll letsencrypt` as normal

**Comment by ANGOmarcello** [comment]
It completed successfully. My browser does not show the new cert yet, but in gitlab pages I can see it.

**Comment by JustinAiken** [comment]
Released new version [0.2.0](https://github.com/JustinAiken/jekyll-gitlab-letsencrypt/releases/tag/v0.2.0) with this functionality

**Comment by To1ne** [comment]
Awesome. I haven't had time to try it out yet.

When I do, I'll try to automate it a bit more with GitLab CI.

**Comment by To1ne** [comment]
And send a PR for that.
